Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 0's token_index 447
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 1's token_index 58
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 2's token_index 504
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 3's token_index 303
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 4's token_index 74
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 5's token_index 499
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 6's token_index 335
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 7's token_index 5
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 8's token_index 151
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 9's token_index 224
Sat 27 May 2017 16:05:54 API.py [line:546] INFO 200 statuses/filter text thread 10's token_index 67
Sat 27 May 2017 16:05:57 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:05:57 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:05:58 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:05:58 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:05:59 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:05:59 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:00 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:00 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:01 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:01 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:04 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:04 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:05 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:07 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:07 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:08 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:08 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:09 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:09 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:14 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:14 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:19 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:19 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 16:06:23 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'195784064', u'user_id': 195784064, u'id': 868377674548469760L, u'id_str': u'868377674548469760'}, u'timestamp_ms': u'1495872378180'}}
Sat 27 May 2017 16:06:24 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:24 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:31 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:31 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:37 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1318426098', u'user_id': 1318426098, u'id': 868376564207165440L, u'id_str': u'868376564207165440'}, u'timestamp_ms': u'1495872383891'}}
Sat 27 May 2017 16:06:37 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'71150938', u'user_id': 71150938, u'id': 868377670723276801L, u'id_str': u'868377670723276801'}, u'timestamp_ms': u'1495872384026'}}
Sat 27 May 2017 16:06:38 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:38 API.py [line:207] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 16:06:39 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'217716435', u'user_id': 217716435, u'id': 868318877322752001L, u'id_str': u'868318877322752001'}, u'timestamp_ms': u'1495872380898'}}
Sat 27 May 2017 16:06:42 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1297146222', u'user_id': 1297146222, u'id': 821742612352794624L, u'id_str': u'821742612352794624'}, u'timestamp_ms': u'1495872381780'}}
Sat 27 May 2017 16:07:10 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'82044662', u'user_id': 82044662, u'id': 868377868975448064L, u'id_str': u'868377868975448064'}, u'timestamp_ms': u'1495872417928'}}
Sat 27 May 2017 16:07:11 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1339385328', u'user_id': 1339385328, u'id': 868377980418088960L, u'id_str': u'868377980418088960'}, u'timestamp_ms': u'1495872421813'}}
Sat 27 May 2017 16:07:50 API.py [line:222] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'236833272', u'user_id': 236833272, u'id': 867115482159222786L, u'id_str': u'867115482159222786'}, u'timestamp_ms': u'1495872436986'}}
